# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup JDK with Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Build with Maven
        run: mvn clean install
